name: Build and Push Docker Image

on: [push]  # runs every push

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_SECRET }}
         
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build with cache
        run: |
          set -e
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new \
            -t ghcr.io/${{ secrets.GIT_USERNAME }}/Simple-DevOps-Project:latest .

      - name: Push Docker Image
        run: |
          set -e
          docker push ghcr.io/${{ secrets.GIT_SECRET }}/Simple-DevOps-Project:latest

      - name: Test Docker image
        run: |
          set -e
          docker run --rm ghcr.io/${{ anderman.niiyii }}/Simple-DevOps-Project:latest curl --version
