name: Build and Push Docker Image

on: [push]  # runs every push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_SECRET }}
         
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build with cache
        run: |
          set -e
          docker buildx build \
            -t ghcr.io/niiyii/devops:latest .
            
      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push (Multi-Arch)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/niiyii/devops:latest --push .
    
      - name: Push Docker Image
        run: |
          set -e
          docker push ghcr.io/niiyii/devops:latest

      - name: Test Docker image
        run: |
          set -e
          docker run --rm ghcr.io/niiyii/devops:latest curl --version
